stages:
  - build
  - test
  - release
  - deploy

variablles:
   IMAGE_NAME: 'mini-projet-gitlab'
   IMAGE_TAG: 'v1'
   DOCKER_USERNAME: 'ulricjsteve'*
   DOCKER_PASSWORD:
   HOST_PORT: 80
   CONTAINER_PORT: 80
   SERVER_USERNAME: 'ubuntu'

Build:
  stage: build
  image: docker:latest
  services:
     - name: docker:dind
       alias: docker
  script:
    - docker build --no-cache -t $IMAGE_NAME:$IMAGE_TAG .
    - docker save -o mini-projet-gitlab.tar $IMAGE_NAME:$IMAGE_TAG
  artifacts:
    paths:
       - mini-projet-gitlab.tar

.test_templates: &test_templates 
  stage: test
  before_script:
    -apk add --no-cache curl
  script:
   - docker load -i mini-projet-gitlab.tar
   - docker run --rm -dp $HOST_POR:$CONTAINER_PORT --name $IMAGE_NAME $IMAGE_NAME:$IMAGE_TAG
   - sleep 5
   - curl -I "http://docker" | grep -i 200

Test:
  stage: test
  image: docker:latest
  services:
   - name: docker:dind
     alias: docker
  <<: *test_templates

.release_image: &release_image
 stage: release
   - docker login -u $DOCKER_USERNAME 
   - docker load -i mini-projet-gitlab.tar
   - docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
   - docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG

Release Image:
   stage: release
   image: docker:latest
   services:
     - name: docker:dind
       alias: docker
  <<: *release_image


   